### ISSUE TITLE
Problems with radiorec on Mac python version 3.6.4

### ISSUE THREAD

**Issue by lastsamurai26** [beedaddy/radiorec#7]
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

./radiorec.py list 
./radiorec.py record 

the same error 

```
Traceback (most recent call last):
  File "./Daten/Programme/radiorec-master/radiorec.py", line 162, in <module>
    main()
  File "./Daten/Programme/radiorec-master/radiorec.py", line 159, in main
    args.func(args)
  File "./Daten/Programme/radiorec-master/radiorec.py", line 130, in list
    settings = read_settings()
  File "./Daten/Programme/radiorec-master/radiorec.py", line 55, in read_settings
    + 'Application Support' + os.sep + 'radiorec'
TypeError: bad operand type for unary +: 'str'
```

**Comment by lastsamurai26** [comment]
I solved the issue

**Comment by beedaddy** [comment]
Thanks a lot!
